# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2022-07-15 22:05:52 krylon>
#
#+TAGS: go(g) internals(i) ui(u) bug(b) feature(f)
#+TAGS: database(d) design(e), meditation(m)
#+TAGS: optimize(o) refactor(r) cleanup(c)
#+TODO: TODO(t)  RESEARCH(r) IMPLEMENT(i) TEST(e) | DONE(d) FAILED(f) CANCELLED(c)
#+TODO: MEDITATE(m) PLANNING(p) | SUSPENDED(s)
#+PRIORITIES: A G D
* Clock
  #+BEGIN: clocktable :scope file :maxlevel 200 :emphasize t
  #+CAPTION: Clock summary at [2022-07-15 Fr 22:05]
  | Headline              | Time       |            |       |       |
  |-----------------------+------------+------------+-------+-------|
  | *Total time*          | *1d 19:58* |            |       |       |
  |-----------------------+------------+------------+-------+-------|
  | *Theseus*             | *1d 19:58* |            |       |       |
  | \_  /Components/      |            | /1d 19:58/ |       |       |
  | \_    Data types      |            |            |  1:04 |       |
  | \_    Database        |            |            |  2:38 |       |
  | \_    Backend         |            |            | 22:01 |       |
  | \_      Notifications |            |            |       | 12:12 |
  | \_      HTTP API      |            |            |       |  4:12 |
  | \_    Frontend        |            |            | 18:15 |       |
  #+END:
* Theseus
** Components
*** Data types                                                    :internals:
    :LOGBOOK:
    CLOCK: [2022-07-01 Fr 17:48]--[2022-07-01 Fr 17:51] =>  0:03
    CLOCK: [2022-06-30 Do 22:10]--[2022-06-30 Do 23:11] =>  1:01
    :END:
*** Database
    :LOGBOOK:
    CLOCK: [2022-07-01 Fr 17:51]--[2022-07-01 Fr 20:08] =>  2:17
    CLOCK: [2022-06-30 Do 23:11]--[2022-06-30 Do 23:32] =>  0:21
    :END:
    Pretty sure I'll use sqlite.
*** GUI
    I /could/ use Gtk, or I could be adventurous and use fyne. I tried it
    before, and it did not work out well, but on the plus side, it is native
    Go, the cgo overhead would go away.

    But after taking a brief look at my fyne experiment, I'll stick with Gtk.
*** Networking?                                          :feature:meditation:
    I could make an attempt to build this as a distributed application so I
    can sync reminders between machines. I think that's a nice idea.
*** Backend
    :LOGBOOK:
    CLOCK: [2022-07-09 Sa 17:39]--[2022-07-09 Sa 17:40] =>  0:01
    CLOCK: [2022-07-04 Mo 17:12]--[2022-07-04 Mo 19:37] =>  2:25
    CLOCK: [2022-07-02 Sa 17:04]--[2022-07-02 Sa 19:06] =>  2:02
    CLOCK: [2022-07-01 Fr 20:56]--[2022-07-01 Fr 22:05] =>  1:09
    :END:
**** TODO Notifications                                             :feature:
     :LOGBOOK:
     CLOCK: [2022-07-12 Di 20:42]--[2022-07-12 Di 23:22] =>  2:40
     CLOCK: [2022-07-11 Mo 20:46]--[2022-07-12 Di 01:03] =>  4:17
     CLOCK: [2022-07-09 Sa 17:40]--[2022-07-09 Sa 22:55] =>  5:15
     :END:
     
**** IMPLEMENT HTTP API
     :LOGBOOK:
     CLOCK: [2022-07-06 Mi 18:27]--[2022-07-06 Mi 20:39] =>  2:12
     CLOCK: [2022-07-05 Di 19:38]--[2022-07-05 Di 21:38] =>  2:00
     :END:
     I decided to use HTTP as my application layer protocol, because it is
     simple and available, and it also leaves open the option to build a web
     based interface later on if I feel like it.
     But for the moment, the "client" is going to be the frontend, so I need
     to think about what operations I need.
     - Add Reminder
     - Delete Reminder
     - Edit Reminder
     - Get all Reminders
     - Get pending Reminders
     - Get new Reminders
*** Frontend                                                             :ui:
    :LOGBOOK:
    CLOCK: [2022-07-15 Fr 20:05]--[2022-07-15 Fr 22:05] =>  2:00
    CLOCK: [2022-07-15 Fr 15:10]--[2022-07-15 Fr 17:44] =>  2:34
    CLOCK: [2022-07-14 Do 19:13]--[2022-07-14 Do 22:44] =>  3:31
    CLOCK: [2022-07-13 Mi 18:51]--[2022-07-13 Mi 21:30] =>  2:39
    CLOCK: [2022-07-09 Sa 17:05]--[2022-07-09 Sa 17:26] =>  0:21
    CLOCK: [2022-07-08 Fr 22:19]--[2022-07-08 Fr 23:26] =>  1:07
    CLOCK: [2022-07-08 Fr 18:42]--[2022-07-08 Fr 21:43] =>  3:01
    CLOCK: [2022-07-07 Do 22:38]--[2022-07-07 Do 22:50] =>  0:12
    CLOCK: [2022-07-07 Do 18:25]--[2022-07-07 Do 21:15] =>  2:50
    :END:

** Bugs
** Questions
